services:
  # FIXME Problem with connectivity to zen-core-db
#  zen-core:
#    build:
#      context: services/core
#      dockerfile: Dockerfile
#    container_name: zen-core
#    ports:
#      - "8080:8080"
  zen-core-db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zen-core
    ports:
      - "5432:5432"
# FIXME Problem with connectivity to flagd
#  zen-message-sender:
#    build:
#      context: services/messagesender
#      dockerfile: Dockerfile
#    container_name: zen-message-sender
#    ports:
#      - "8081:8081"
#  management-system-flagd:
#    image: ghcr.io/open-feature/flagd:latest
#    container_name: flagd
#    ports:
#      - "8013:8013"
#    volumes:
#      - ./flags.flagd.json:/etc/flagd/flags.json
#    command: ["start", "--uri=file:/etc/flagd/flags.json", "--port 8013"]
  zen-kafka:
    build:
      context: environment/kafka
      dockerfile: Dockerfile
    container_name: zen-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,EXTERNAL://kafka_b:9094
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NUM_PARTITIONS=2